GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO PUBLIC;

GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO PUBLIC;

GO
GRANT CONNECT TO [LBS\SVC-SCOM-SQLMON];

GO
GRANT CONNECT TO [LBS\TP_AAdel];

GO
GRANT CONNECT TO [LBS\TP_MLozada];

GO
GRANT CONNECT TO [Pest_Services];

--GO
--GRANT CONNECT TO [lbs_user];

GO
GRANT EXECUTE TO [proc_executor];

GO
GRANT CONNECT TO [LBS-MFS-01\SSRS_User];