CREATE TABLE [Inspection].[DeletedInspection] (
    [InspectionId]         INT             NOT NULL,
    [AltInspectionId]      INT             NULL,
    [InspectionDate]       DATETIME        NULL,
    [AmPm]                 CHAR (2)        NULL,
    [OfficerId]            INT             NULL,
    [AssignedBy]           INT             NULL,
    [DateAssigned]         DATETIME        NULL,
    [PropertyId]           INT             NULL,
    [TenantId]             INT             NULL,
    [BlockCycleId]         INT             NULL,
    [VisitTypeId]          INT             NULL,
    [NoAccessId]           INT             NULL,
    [NoAccessTime]         DATETIME        NULL,
    [DiaryId]              INT             NULL,
    [InspectionStartTime]  DATETIME        NULL,
    [InspectionEndTime]    DATETIME        NULL,
    [Telephone]            VARCHAR (20)    NULL,
    [InsectMonitorsFound]  INT             NULL,
    [BaitPointsFound]      INT             NULL,
    [HygieneLevelId]       INT             NULL,
    [FollowUpDate]         DATETIME        NULL,
    [FollowUpAmPm]         CHAR (2)        NULL,
    [FollowUpId]           INT             NULL,
    [FollowUpNotes]        VARCHAR (2000)  NULL,
    [FollowUpInspectionId] INT             NULL,
    [JobClosed]            BIT             CONSTRAINT [DF__DeletedIn__JobCl__45A94D10] DEFAULT ((0)) NOT NULL,
    [AmountPaid]           MONEY           NULL,
    [PaymentTypeId]        INT             NULL,
    [Notes]                VARCHAR (2000)  NULL,
    [TenantSignature]      VARBINARY (MAX) NULL,
    [OfficerSignature]     VARBINARY (MAX) NULL,
    [LastUpdated]          DATETIME        CONSTRAINT [DF__DeletedIn__LastU__469D7149] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]        INT             NULL,
    [StatusId]             INT             NOT NULL,
    [Deleted]              BIT             CONSTRAINT [DF__DeletedIn__Delet__47919582] DEFAULT ((0)) NOT NULL
);

